### ISSUE TITLE
[FEATURE] - ADD OPTIONAL CERTIFICATE MANIFEST CREATION

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/s3-minio-config#11]
ADD OPTIONAL CERTIFICATE CREATION WITH TERRAFORM MODULE

IN ADDITION TO THE HELM CHART WE HAVE TO APPLY TWO CERTIFICATE MANIFESTS:
- [x] TEST TERRAFORM MOUDLES kubectl_manifest AND kubectl_path_documents - CHECK EXAMPLES FOR MODULE kubectl_manifest / kubectl_path_documents TO GET FAMILIAR WITH CREATING K8S MANIFEST W/ TERRAFORM
- [x] ADD BRANCH WITH feaure/issue-11/ PREFIX (SEE WORKFLOWS IN THIS REPO)
- [x] ADD CERT FOR CONSOLE AND API (BEST WOULD BE ONE DEFINITION WITH 2 RUNS - DONT REPEAT OURSELFS MANIFEST STRUCTURE IS THE SAME)
- [x] USE VARIABLES INSIDE MANIFEST (SEE EXAMPLE FLUX LINK - TAKE CARE ITS PART OF A HELM CHART RENDERING, ITS SIMILAR BUT NOT 100% THE MANIFEST FORM - SEE EXAMPLE BELOW FOR REAL MAIFEST)
- [x] ADD CONDITION FOR CREATION OF CERTIFICATE LIKE create_cert 
- [x] REUSE VARIABLES FROM HELM DEPLOYMENT (INGRESS, UNUSED ISSUER NAME)

REFERENCE:

[FLUX](https://github.com/stuttgart-things/stuttgart-things/blob/main/apps/minio/pre-release.yaml)
[DOCS](https://stuttgart-things.github.io/docs/docs/terraform/)

```
# EXAMPLE RENDERED/EXISTING MANIFEST 

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{ var.name }}
  namespace: {{ var.namespace  }}
spec:
  commonName: {{ var.name + var.domain  }}
  dnsNames:
    - {{ var.name + var.domain  }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ var.nameClusterIssuer  }}
  secretName: {{ varSecretName  }}
```
