### ISSUE TITLE
[FEATURE] - DEPLOY MINIO W/ HELM MODULE

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/s3-minio-config#7]
in addition to our gitops deployments w/ flux we want to deploy minio on kubernetes on helm (and terraform) w/ this module.

* deployment should be an optional task (boolean switch + values) in this module
* values should be rendered from a template file (see tf-helm2 example in link) 

* example template
```
# ./templates/minio-values.tpl
persistence:
  enabled: ${helmStorageEnabled}
  storageClass: ${storageClass}
# ...
# see link minio-values-sthings
```
* example values

```hcl
enableMinnioDeployment = true
helmStorageEnabled = true
storageClass = trident
```

see:
[minio-values-sthings](https://github.com/stuttgart-things/stuttgart-things/blob/main/apps/minio/release.yaml)
[tf-helm](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release)
[tf-helm2](https://getbetterdevops.io/terraform-with-helm)
